// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"MoonAgent/pkg/config"
	"MoonAgent/pkg/embedder"
	"MoonAgent/pkg/es8"
	"MoonAgent/pkg/indexer"
	"MoonAgent/pkg/retriever"
	es8_2 "github.com/cloudwego/eino-ext/components/indexer/es8"
)

// Injectors from wire.go:

// InitializeApplication 是我们的 injector 函数
// 它声明了我们想构建 *Application，并列出了所有的 Provider
func InitializeApplication() (*Application, func(), error) {
	serverConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	client, err := es8.ProvideEs8Client(serverConfig)
	if err != nil {
		return nil, nil, err
	}
	arkEmbedder, err := embedder.ProvideEmbedder(serverConfig)
	if err != nil {
		return nil, nil, err
	}
	es8Retriever, err := retriever.ProvideRetriever(client, arkEmbedder)
	if err != nil {
		return nil, nil, err
	}
	indexerConfig := indexer.NewIndexerConfig(client, arkEmbedder)
	context := ProvideContext()
	es8Indexer, err := es8_2.NewIndexer(context, indexerConfig)
	if err != nil {
		return nil, nil, err
	}
	application := ProvideApplication(serverConfig, client, arkEmbedder, es8Retriever, indexerConfig, es8Indexer)
	return application, func() {
	}, nil
}
