// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"MoonAgent/pkg/embedder"
	"MoonAgent/pkg/milvus"
	"MoonAgent/pkg/retriever"
)

// Injectors from wire.go:

// InitializeApplication 是我们的 injector 函数
// 它声明了我们想构建 *Application，并列出了所有的 Provider
func InitializeApplication() (*Application, func(), error) {
	client, err := milvus.ProvideMilvusClient()
	if err != nil {
		return nil, nil, err
	}
	arkEmbedder, err := embedder.ProvideEmbedder()
	if err != nil {
		return nil, nil, err
	}
	milvusRetriever, err := retriever.ProvideRetriever(client, arkEmbedder)
	if err != nil {
		return nil, nil, err
	}
	application := ProvideApplication(client, arkEmbedder, milvusRetriever)
	return application, func() {
	}, nil
}
