// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

// Injectors from wire.go:

// InitializeApplication 是我们的 injector 函数
// 它声明了我们想构建 *Application，并列出了所有的 Provider
func InitializeApplication() (*Application, func(), error) {
	client, err := ProvideMilvusClient()
	if err != nil {
		return nil, nil, err
	}
	embedder, err := ProvideEmbedder()
	if err != nil {
		return nil, nil, err
	}
	retriever, err := ProvideRetriever(client, embedder)
	if err != nil {
		return nil, nil, err
	}
	application := ProvideApplication(client, embedder, retriever)
	return application, func() {
	}, nil
}
